### ISSUE TITLE
2. I, as an Admin, can see list of all products

### ISSUE THREAD

**Issue by valeriia-danylenko** [ITA-Dnipro/Dp-202-shop#5]
- [x] #14 2.1 Create Products Class 
- [x] #12 2.2 Create Hash Middleware
 - [x] #13 2.3 Admin MVC Products
