### ISSUE TITLE
10. I, as User, can register as a salesman

### ISSUE THREAD

**Issue by CurlyAnastasi** [ITA-Dnipro/Dp-202-shop#54]
- [x] #48 Create registration MVC
- [x] #49 Create User MVC
- [x] #50 Create route for salesman registration
