### ISSUE TITLE
3. I, as an Admin, can add new product to shop

### ISSUE THREAD

**Issue by so2niko** [ITA-Dnipro/Dp-202-shop#6]
- [x] #15 3.1 Create get request to admin-products-add
- [x] #16 3.2 Joi middleware (check for valid data)
- [x] #17 3.3 Create findOrCreate method 
- [x] #18 3.4 Method AddProduct
