### ISSUE TITLE
16. I, as Salesman, can mark completed orders

### ISSUE THREAD

**Issue by CurlyAnastasi** [ITA-Dnipro/Dp-202-shop#67]
- [x] #66 Add status column to DB
- [x] #68 Create user/orders/:id route
- [x] #69 Create PUT request to mark completed orders
