### ISSUE TITLE
4. I, as an Admin, can edit products in shop

### ISSUE THREAD

**Issue by so2niko** [ITA-Dnipro/Dp-202-shop#7]
- [x] #29 Implement search/filter on products 
- [x] #19 GET route products id
- [x] #20 PUT route products id
